include:
  remote: https://github.com/elct9620/ruby-gitlab-ci/raw/main/rails.yml

variables:
  RUBY_VERSION: 2.7.4
  ASSETS_PRECOMPILE: 'yes'
  RSPEC_JUNIT_REPORT: 'no'

rspec:
  rules:
    - if: $CI_MERGE_REQUEST_ID
