version: '3.4'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:13.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  application:
    image: registry.gitlab.com/jhang-jhe-wei/kugifoods-rails
    environment:
      - RAILS_SERVE_STATIC_FILES=yes
      - AUTO_MIGRATION=yes
      - DATABASE_URL=postgres://boxing:boxing@postgres/boxing
      - RAILS_MASTER_KEY=c81459c3504a0fafbc2ec82beacb05ce
    ports:
      - "3000:3000"
    depends_on:
      - postgres
